#!/usr/bin/env python3
# numbers
# provides information on a given number on the command line
# usage : numbers n
#         Where n is a number you are curious about

import requests
import sys
import json

number = sys.argv[1]
request_type = "math"
url = "https://numbersapi.p.rapidapi.com/" + number + "/" + request_type + "/"

querystring = {"json":"true"}

headers = {
    'x-rapidapi-host': "numbersapi.p.rapidapi.com",
    'x-rapidapi-key': "c68c73025bmsh47ccb345ec563dap1d4992jsnbe5452a4b59c"
    }

response = requests.request("GET", url, headers=headers, params=querystring)

information = json.loads(response.text)

print(information['text'])
